### ISSUE TITLE
Additional properties in model validaton should be stripped or raise an error imo

### ISSUE THREAD

**Issue by joaomarccos** [flasgger/flasgger#386]
Given a definition: (swagger 2.0)

```
User:
        type: object
        required:
          - name
        properties:
          name:
            type: string
            description: The name of user. Must be unique
```

When we send in request body:` {name: 'João', other_stuff: 'stuff'} ` the validation should fail since we have unknow properties included in the sent object.
