### ISSUE TITLE
Swagger UI Does Not Allow Entry of a nullable integer

### ISSUE THREAD

**Issue by Anti-Distinctlyminty** [flasgger/flasgger#403]
I have a patch function with an OpenAPI query parameter defined as nullable
```yaml
-   in: query
    name: someId
    schema:
         type: integer
         nullable: true
```
I am able to call this via curl `curl -X PATCH "http://0.0.0.0:5000/apiPath?someId=null"
and `someId` will appear as a string `'null'` and if I try to use the Swagger UI to pass `null` it refuses to do so, showing a red background as though the value is not allowed.
![image](https://user-images.githubusercontent.com/1378483/83027878-fb1bd100-a030-11ea-8860-19310934fe87.png)

Shouldn't `null` values be represented as `None` when contained in the `flask.request.args` MultiDict?
