### ISSUE TITLE
Importing references from other yml

### ISSUE THREAD

**Issue by lohwanjing** [flasgger/flasgger#423]
I'm using flasgger with flask-restful and I'm wondering if its possible to import definitions from another file. This is so I can have ymls for each of my methods, while the common definitions can be in a separate definitions.yml. I'm getting a "Could not resolve reference error"

Other approaches that help improve the maintainability by not having to define the same schema multiple times are also welcome

Resource class
```
class CreateUser(Resource)
    @swag_from('create_user.yml', validation=true)
    def post(self):
    <code>
```

create_user.yml (working)
```
---
parameters:
    - in: body
      name: body
      schema:
          id: User
          type: object
          required:
          - name
         properties:
           name:
           type: string
```

create_user.yml (Not working, but preferred)
```
---
parameters:
    - in: body
      name: body
      schema:
          $ref: '#/definitions/User'
import: './definitions.yml'
```

definitions.yml (Not working, but preferred)
```
---
definitions:
    User:
        type: object
        required:
          - name
        properties:
           name:
           type: string
```
