### ISSUE TITLE
Query params validation with openApi v3

### ISSUE THREAD

**Issue by ritabiniash** [flasgger/flasgger#518]
I am trying to add a validation on my routes with` swag_from`. I want to use an existing `.yaml`, and for the validation I need to add a validation scheme. 

This is how my route is configured in `api.yaml`:

```
paths:
  /user/suggestions:
    get:
      summary: Returns search suggestions for user
      operationId: src.api.user.api.get_suggestions
      parameters:
        - in: query
          name: search
          schema:
            type: string
          description: The search term
        - in: query
          name: limit
          schema:
            type: integer
          description: The number of results to be returned
        - in: query
          name: lookback
          schema:
            type: integer
          description: How many days back to retrieve
```

How do I convert the restrictions from parameters to a scheme so 
`@swag_from('api.yaml', validation=True, schema_id='suggestion_validation')`
will validate my query params ? 

Haven't found any example in the documentation so any help would be appreciated :)
